# Generated by Django 2.1.3 on 2018-12-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20181206_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(help_text='微信用户绑定和CC视频统计', max_length=64, unique=True),
        ),
    ]
